name: blackjack_poker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21
  web:
    generate: false

flutter_native_splash:
  color: "#1a1a2e"
  image: assets/icon/icon.jpg
  android: true
  ios: true
  fullscreen: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
